<Project Sdk="Microsoft.NET.Sdk.Web">



    <PropertyGroup>
      <UserSecretsId>fb88295d-76d5-4d3e-913b-c54d49008083</UserSecretsId>
    </PropertyGroup>



    <ItemGroup>
      <Folder Include="Domain\EntityRepository\" />
    </ItemGroup>



    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>



    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Account\Login.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Account\Logout.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Account\Register.cshtml" />
    </ItemGroup>

</Project>
